# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch

nm = torch.rand(7,7)
nm


tensor([[0.2694, 0.9269, 0.5555, 0.8306, 0.9763, 0.3979, 0.8144],
        [0.7713, 0.8654, 0.1576, 0.2734, 0.8719, 0.6605, 0.1854],
        [0.1566, 0.4737, 0.6595, 0.2916, 0.7647, 0.6318, 0.3899],
        [0.1697, 0.4685, 0.2916, 0.4348, 0.4746, 0.1459, 0.2640],
        [0.2344, 0.2735, 0.0372, 0.5032, 0.7541, 0.7855, 0.6106],
        [0.8384, 0.9741, 0.7015, 0.7162, 0.0396, 0.1498, 0.2175],
        [0.0565, 0.0756, 0.4368, 0.0877, 0.2164, 0.8920, 0.9592]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
ten = torch.rand(1,7)
ten_1 = torch.rand(1,7)

mm = torch.mm(ten, ten_1.T)
mm


tensor([[1.8868]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
import torch
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)


ten = torch.rand(7,7)
ten_1 = torch.rand(7,1)


mm = torch.matmul(ten, ten_1)
mm, mm.size()


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
import torch
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
import torch
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)


tota = torch.rand(2,3)
tota_1 = torch.rand(2,3)



device  = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

lol_1 = tota.to(device)
lol_2 = tota_1.to(device)

print(lol_1, lol_2)

cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [30]:
gg = torch.matmul(lol_1, lol_2.T)
gg, gg.size()


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [32]:
gg.max(), gg.min()

(tensor(0.5617), tensor(0.3647))

### 9. Find the maximum and minimum index values of the output of 7.

In [33]:
gg.argmax(), gg.argmin()


(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [34]:
import torch
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)


a = torch.rand(1,1,1,10)


a_sq = a.squeeze()
a, a.size(), a_sq, a_sq.size()


# Print out tensors and their shapes


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))